source 'https://rubygems.org'

git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

ruby '2.6.6'

gem 'rails', '~> 5.1'
gem 'kaminari', '~> 1.1.1'
gem 'garb', '0.9.8'
gem 'cocaine', '0.5.5'
gem 'mysql2', '0.5.2'
gem 'rest-client', '1.6.7'
gem 'ancestry', '~> 2.1'
gem 'eventmachine', '~> 1.2.7'
gem 'gabba', '~> 1.0.1'
gem 'json', '~> 2.1.0'
gem 'airbrake', '~> 10.0.0'
gem 'airbrake-ruby', '~> 4.12.0'
gem 'newrelic_rpm', '~> 6.5.0.357'
gem 'redis', '~> 4.1.2'
gem 'rails-deprecated_sanitizer', '~> 1.0.3'
gem 'actionpack-page_caching', '~> 1.2.0'
gem 'responders', '~> 3.0.0'
gem 'aws-sdk-s3', '~> 1.0.0.rc2'
gem 'rack-timeout', '~> 0.3.0'
gem 'iconv', '~> 1.0.8'
gem 'redis-rails', '~> 5.0.2'
gem 'sitemap_generator', '~> 3.1.0'
gem 'fastercsv', '~> 1.5.5'
gem 'comma', '~> 3.0'
gem 'feedjira', '~> 3.1.0'
gem 'mechanize', '~> 2.5.1'
gem 'paperclip', '~> 6.0.0'
gem 'public_suffix', '~> 3.1.1'
gem 'rb-inotify', '~> 0.9.10'
gem 'nested_form', '0.3.2'
gem 'will_paginate', '~> 3.0.pre2'
gem 'signet', '0.11.0'
gem 'ai4r', '~> 1.12'
gem 'omniauth-facebook'
gem 'mobile-fu', '~> 1.4.0'
gem 'configatron', '3.2.0'
gem 'text', '~> 1.2.3'
gem 'canonical-rails', '~> 0.2.6'
gem 'passenger', '>= 5.0.25', require: 'phusion_passenger/rack_handler'
gem 'elasticsearch-model'
gem 'patron', '~> 0.13.3'
gem 'devise', '~> 4.7.1'
gem 'uglifier', '~> 4.2.0'
gem 'coffee-rails', '~> 5.0.0'
gem 'sass-rails', '~> 6.0.0'
gem 'bootsnap', '>= 1.4.2', require: false
gem "asset_sync", '~> 2.0.0'
gem "fog-aws", '~> 2.0.1'
gem 'sprockets-rails', '~> 3.2.1'
gem 'record_tag_helper', '~> 1.0'
gem 'jquery-rails', '~> 4.3.5'
gem 'turbolinks', '~> 5.2.1'
gem 'tinymce-rails', '~> 5.1.5'
gem "bunny", ">= 2.14.1"